import { beforeAll, beforeEach, describe, test, expect, vi } from 'vitest'
import { schema } from 'markupeditor/src/schema/index.js'
import { MU } from 'markupeditor'
import '../src/markup-editor-markdown.js'

// ---------------------------------------------------------------------------
// Module setup
//
// Since 303c562 moved markdown import/export from a plugin to a userscript,
// markup-editor-markdown.js attaches exportMarkdown/importMarkdown directly
// onto the real MU singleton imported from the markupeditor package, rather
// than exporting them or registering via MU.registerPlugin. Importing the
// module (above) triggers that attachment; MU.activeView is stubbed per test.
// ---------------------------------------------------------------------------

const exportFn = MU.exportMarkdown
const importFn = MU.importMarkdown
let activeViewSpy

beforeAll(() => {
  activeViewSpy = vi.spyOn(MU, 'activeView')
})

beforeEach(() => {
  activeViewSpy.mockReturnValue({ state: { schema } })
})

// ---------------------------------------------------------------------------
// exportFn — envelope structure
// ---------------------------------------------------------------------------

describe('exportFn — no active view', () => {
  test('returns result:null and a warning when MU has no active view', () => {
    activeViewSpy.mockReturnValue(null)
    const envelope = JSON.parse(exportFn('unused'))
    expect(envelope.result).toBeNull()
    expect(Array.isArray(envelope.warnings)).toBe(true)
    expect(envelope.warnings.length).toBeGreaterThan(0)
  })
})

describe('exportFn — plain document', () => {
  test('result is a string and warnings is an empty array', () => {
    const doc = schema.nodes.doc.create(null, [
      schema.nodes.paragraph.create(null, [schema.text('Hello')])
    ])
    activeViewSpy.mockReturnValue({ state: { doc } })
    const envelope = JSON.parse(exportFn('unused'))
    expect(typeof envelope.result).toBe('string')
    expect(Array.isArray(envelope.warnings)).toBe(true)
    expect(envelope.warnings).toHaveLength(0)
  })
})

// ---------------------------------------------------------------------------
// exportFn — warnings flow through to the envelope
//
// These mirror the per-feature cases in warnings.test.js but call exportFn
// so we verify that warnings generated by the serializer are not dropped
// before JSON.stringify — the contract that PluginResult.decode() depends on.
// ---------------------------------------------------------------------------

describe('exportFn — warnings in envelope', () => {
  test('image with width attribute: result contains <img> tag, no warning', () => {
    const doc = schema.nodes.doc.create(null, [
      schema.nodes.paragraph.create(null, [
        schema.nodes.image.create({ src: 'photo.jpg', alt: 'photo', width: 200, height: null })
      ])
    ])
    activeViewSpy.mockReturnValue({ state: { doc } })
    const envelope = JSON.parse(exportFn('unused'))
    expect(envelope.result).not.toBeNull()
    expect(envelope.warnings).toHaveLength(0)
    expect(envelope.result).toContain('<img')
  })

  test('underline mark: warning appears in envelope, text is preserved in result', () => {
    const doc = schema.nodes.doc.create(null, [
      schema.nodes.paragraph.create(null, [
        schema.text('underlined', [schema.marks.u.create()])
      ])
    ])
    activeViewSpy.mockReturnValue({ state: { doc } })
    const envelope = JSON.parse(exportFn('unused'))
    expect(envelope.result).toContain('underlined')
    expect(envelope.warnings.length).toBeGreaterThan(0)
  })
})

// ---------------------------------------------------------------------------
// importFn — envelope structure
// ---------------------------------------------------------------------------

describe('importFn — envelope structure', () => {
  test('result is a string and warnings is an array for plain markdown', () => {
    const envelope = JSON.parse(importFn('# Hello\n\nSome text.'))
    expect(typeof envelope.result).toBe('string')
    expect(Array.isArray(envelope.warnings)).toBe(true)
  })

  test('result contains HTML for a simple paragraph', () => {
    const envelope = JSON.parse(importFn('Hello world'))
    expect(envelope.result).toMatch(/<p[^>]*>Hello world<\/p>/i)
  })

  test('empty markdown produces non-null result and empty warnings', () => {
    const envelope = JSON.parse(importFn(''))
    expect(envelope.result).not.toBeNull()
    expect(envelope.warnings).toHaveLength(0)
  })
})

// ---------------------------------------------------------------------------
// importFn — embedded HTML warnings
//
// The parser strips raw HTML and emits a warning for each occurrence.
// These tests verify the warning flows through to the envelope and that the
// HTML content is absent from the result.
// ---------------------------------------------------------------------------

describe('importFn — embedded HTML warnings', () => {
  test('block HTML emits a warning and is stripped from result', () => {
    const envelope = JSON.parse(importFn('Before\n\n<div>blocked</div>\n\nAfter'))
    expect(envelope.warnings.length).toBeGreaterThan(0)
    expect(envelope.warnings.some(w => w.toLowerCase().includes('html block'))).toBe(true)
    expect(envelope.result).not.toContain('blocked')
  })

  test('inline HTML emits a warning and is stripped from result', () => {
    const envelope = JSON.parse(importFn('text <span>inline</span> more'))
    expect(envelope.warnings.length).toBeGreaterThan(0)
    expect(envelope.warnings.some(w => w.toLowerCase().includes('html inline'))).toBe(true)
    expect(envelope.result).not.toContain('<span>')
  })
})

describe('importFn — img tag import', () => {
  test('mid-document block <img> with all attrs becomes image node; no warning (AC-3/AC-7)', () => {
    const envelope = JSON.parse(importFn('# Heading\n\n<img src="logo.png" alt="logo" width="200" height="100">\n\nParagraph.'))
    expect(envelope.warnings).toHaveLength(0)
    expect(envelope.result).toContain('src="logo.png"')
    expect(envelope.result).toContain('alt="logo"')
    expect(envelope.result).toContain('width="200"')
    expect(envelope.result).toContain('height="100"')
  })

  test('inline <img> within paragraph text becomes image node; no warning', () => {
    const envelope = JSON.parse(importFn('Some text <img src="icon.png" alt="icon"> more text.'))
    expect(envelope.warnings).toHaveLength(0)
    expect(envelope.result).toContain('src="icon.png"')
    expect(envelope.result).toContain('alt="icon"')
  })

  test('mid-document block <img> without dimensions: src and alt preserved, no width/height (AC-9)', () => {
    const envelope = JSON.parse(importFn('# Heading\n\n<img src="logo.png" alt="logo">\n\nParagraph.'))
    expect(envelope.warnings).toHaveLength(0)
    expect(envelope.result).toContain('src="logo.png"')
    expect(envelope.result).toContain('alt="logo"')
    expect(envelope.result).not.toMatch(/width="\d+"|height="\d+"/)
  })
})
